controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  imu_sensor_controller:
    type: imu_sensor_controller/ImuSensorController
    publish_rate: 100
  ocs2_controller:
    type: quad_ros/Ocs2Controller
